# Generated by Django 3.1.5 on 2021-01-31 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landscape',
            name='description',
            field=models.CharField(default='text', max_length=500),
            preserve_default=False,
        ),
    ]
