# Generated by Django 3.1.5 on 2021-01-31 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_landscape_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landscape',
            name='description',
        ),
        migrations.AddField(
            model_name='landscape',
            name='text',
            field=models.TextField(default='text'),
            preserve_default=False,
        ),
    ]
