# Generated by Django 3.1.5 on 2021-01-31 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210129_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='texturl',
            field=models.CharField(default='text', max_length=100),
            preserve_default=False,
        ),
    ]
